### ISSUE TITLE
Remove custom future package and add dependency to future library

### ISSUE THREAD

**Issue by coderatchet** [anomaly/prestans3#27]
After some thought (by @devraj), the future library is a commonly depended on library and even included in many unix distributions by default. Depending on this library should not cause too great an issue for users.

**Comment by devraj** [comment]
Both `modernize` and `futurize` seem to be [well endorsed](https://docs.python.org/3/howto/pyporting.html) by the Python community. On OSX and Ubuntu they seem to present by default.

**Comment by coderatchet** [comment]
pulled into master #29
